# fly.toml app configuration file generated for toique on 2026-04-17T14:10:25+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'toique'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile.fly'

[deploy]
  release_command = 'npx drizzle-kit migrate'

[env]
  DRIZZLE_MIGRATIONS_DIR = './db/migrations'
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
