name: Gitleaks Action

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: gitleaks-action-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write # PRにコメント・アノテーションを付与するために必要

jobs:
  gitleaks-action:
    name: Gitleaks PR Annotation
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Gitleaks Action
        uses: zricethezav/gitleaks-action@98e4eb72186985a9bc6dfa2cebdc63b27b9c9ba2 # v2.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-path: .gitleaks.toml
